# Generated by Django 6.0.4 on 2026-06-07 11:32

from django.db import migrations, models


def make_duplicate_emails_unique(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    seen_emails = set()

    for user in User.objects.order_by('id'):
        email = (user.email or '').strip().lower()
        if not email:
            continue

        if email not in seen_emails:
            if user.email != email:
                user.email = email
                user.save(update_fields=['email'])
            seen_emails.add(email)
            continue

        local_part, separator, domain = email.partition('@')
        if not separator:
            local_part = email
            domain = 'example.local'

        candidate = f'{local_part}+user{user.id}@{domain}'
        suffix = 1
        while candidate in seen_emails or User.objects.filter(email__iexact=candidate).exclude(id=user.id).exists():
            candidate = f'{local_part}+user{user.id}-{suffix}@{domain}'
            suffix += 1

        user.email = candidate
        user.save(update_fields=['email'])
        seen_emails.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_email_verified'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='otpcode',
                    name='attempt_count',
                    field=models.PositiveSmallIntegerField(default=0),
                ),
            ],
            database_operations=[],
        ),
        migrations.RunPython(make_duplicate_emails_unique, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
