# Generated by Django 6.0.4 on 2026-06-07 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_otpcode_attempt_count_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=191)),
                ('otp_code', models.CharField(max_length=6)),
                ('reset_token', models.CharField(blank=True, db_index=True, max_length=128)),
                ('is_used', models.BooleanField(default=False)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'is_used'], name='accounts_pa_email_dfc7db_idx'), models.Index(fields=['otp_code', 'is_used'], name='accounts_pa_otp_cod_9fa708_idx'), models.Index(fields=['reset_token', 'is_used'], name='accounts_pa_reset_t_f76d1d_idx'), models.Index(fields=['created_at'], name='accounts_pa_created_2b9495_idx')],
            },
        ),
    ]
