"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

try:
    from dotenv import load_dotenv
except ImportError:
    load_dotenv = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

if load_dotenv:
    load_dotenv(BASE_DIR / '.env')
else:
    env_path = BASE_DIR / '.env'
    if env_path.exists():
        for line in env_path.read_text(encoding='utf-8').splitlines():
            normalized = line.strip()
            if not normalized or normalized.startswith('#') or '=' not in normalized:
                continue

            key, value = normalized.split('=', 1)
            os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#!tn90@s-zb3ffqx&34t^veb0b+xas_1*803p9y@@sk7_ify(&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# In development we keep host checking open to simplify
# testing from localhost, Android emulators and physical devices.
if DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',

      'accounts',
    'pharmacies',
    'medicaments',
    'reservations',
    'deliveries',
    'payments',
    'transactions',
    'invoices',
    'refunds',
    'subscriptions',
    'finance',
    'notifications_app',
    'reviews',


]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 3,
    'EXCEPTION_HANDLER': 'config.exception_handlers.api_exception_handler',

    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'pharmalocate_db',
        'USER': 'pharmalocate_user',
        'PASSWORD': 'motdepasse123',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
CORS_ALLOW_ALL_ORIGINS = True

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.User'

DELIVERY_BASE_FEE = os.getenv('DELIVERY_BASE_FEE', '0.00')
DELIVERY_PRICE_PER_KM = os.getenv('DELIVERY_PRICE_PER_KM', '50.00')
MANUAL_PAYMENT_COMMISSION_RATE = os.getenv(
    'MANUAL_PAYMENT_COMMISSION_RATE',
    '0.00',
)

OTP_DEBUG_PRINT = os.getenv('OTP_DEBUG_PRINT', 'True').lower() in {
    '1',
    'true',
    'yes',
    'on',
}

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'gangueoumar075@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', 'zhlstcwoapaxfrkl').replace(' ', '')
DEFAULT_FROM_EMAIL = os.getenv(
    'DEFAULT_FROM_EMAIL',
    f'PharmaLocate <{EMAIL_HOST_USER}>' if EMAIL_HOST_USER else 'PharmaLocate',
)

_EMAIL_PASSWORD_PLACEHOLDER ='zhlstcwoapaxfrkl'

# EMAIL_BACKEND_MODE: smtp | console | dummy
_email_backend_env = os.getenv('EMAIL_BACKEND_MODE', 'smtp').lower()

# Bascule automatique en console si le placeholder n'a pas été remplacé
if EMAIL_HOST_PASSWORD == _EMAIL_PASSWORD_PLACEHOLDER:
    _email_backend_env = 'console'

if _email_backend_env == 'console':
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
elif _email_backend_env == 'dummy':
    EMAIL_BACKEND = 'django.core.mail.backends.dummy.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Startup diagnostics
print('EMAIL_HOST_USER    =', EMAIL_HOST_USER or 'MANQUANT')
print(
    'EMAIL_HOST_PASSWORD=',
    f'present ({len(EMAIL_HOST_PASSWORD)} chars)' if EMAIL_HOST_PASSWORD and EMAIL_HOST_PASSWORD != _EMAIL_PASSWORD_PLACEHOLDER else 'NON CONFIGURE (placeholder)',
)
print('EMAIL_BACKEND      =', EMAIL_BACKEND)
print('OTP_DEBUG_PRINT    =', OTP_DEBUG_PRINT)

if EMAIL_HOST_PASSWORD == _EMAIL_PASSWORD_PLACEHOLDER or not EMAIL_HOST_PASSWORD:
    print()
    print('!' * 60)
    print('ATTENTION : Gmail SMTP non configure !')
    print('  Les OTPs seront affiches dans ce terminal uniquement.')
    print('  Pour envoyer les emails par Gmail :')
    print('  1. myaccount.google.com -> Securite -> Validation 2 etapes')
    print('  2. Mots de passe des applications -> Creer -> PharmaLocate')
    print('  3. Mettre le code 16 chars dans .env EMAIL_HOST_PASSWORD=')
    print('  4. Garder EMAIL_BACKEND_MODE=smtp dans .env')
    print('!' * 60)
    print()
