# Generated by Django 6.0.4 on 2026-06-09 14:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacies', '0007_alter_pharmacy_coordinates_nullable'),
        ('reservations', '0003_reservation_frais_livraison_reservation_mode_retrait_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_livraison', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('note', models.TextField(blank=True)),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_preparation', 'En preparation'), ('livreur_assigne', 'Livreur assigne'), ('en_route', 'En route'), ('livree', 'Livree'), ('annulee', 'Annulee'), ('echec_livraison', 'Echec livraison')], db_index=True, default='en_attente', max_length=30)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_livraison_estimee', models.DateTimeField(blank=True, null=True)),
                ('date_livraison_reelle', models.DateTimeField(blank=True, null=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='pharmacies.pharmacy')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='reservations.reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(blank=True, choices=[('en_attente', 'En attente'), ('en_preparation', 'En preparation'), ('livreur_assigne', 'Livreur assigne'), ('en_route', 'En route'), ('livree', 'Livree'), ('annulee', 'Annulee'), ('echec_livraison', 'Echec livraison')], max_length=30)),
                ('nouveau_statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_preparation', 'En preparation'), ('livreur_assigne', 'Livreur assigne'), ('en_route', 'En route'), ('livree', 'Livree'), ('annulee', 'Annulee'), ('echec_livraison', 'Echec livraison')], max_length=30)),
                ('commentaire', models.TextField(blank=True)),
                ('date_changement', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_status_changes', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='deliveries.delivery')),
            ],
            options={
                'verbose_name': 'Historique statut livraison',
                'verbose_name_plural': 'Historiques statuts livraison',
                'ordering': ['-date_changement'],
            },
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['statut', 'date_creation'], name='deliveries__statut_0b0e0b_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['pharmacy', 'statut'], name='deliveries__pharmac_1264a6_idx'),
        ),
    ]
