# Generated by Django 6.0.4 on 2026-06-14 12:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Distance estimee entre la pharmacie et le client.', max_digits=8),
        ),
        migrations.AddField(
            model_name='delivery',
            name='tarif_par_km',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Tarif utilise pour calculer les frais de livraison.', max_digits=10),
        ),
    ]
