# Generated by Django 6.0.4 on 2026-06-09 15:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0002_default_payment_methods'),
        ('pharmacies', '0007_alter_pharmacy_coordinates_nullable'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('prix_mensuel', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('prix_annuel', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('max_medicaments', models.PositiveIntegerField(default=50)),
                ('visibilite_prioritaire', models.BooleanField(default=False)),
                ('statistiques_avancees', models.BooleanField(default=False)),
                ('badge_premium', models.BooleanField(default=False)),
                ('notifications_prioritaires', models.BooleanField(default=False)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan abonnement',
                'verbose_name_plural': 'Plans abonnement',
                'ordering': ['prix_mensuel', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='PharmacySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('active', 'Active'), ('expiree', 'Expiree'), ('annulee', 'Annulee'), ('en_attente_paiement', 'En attente paiement')], db_index=True, default='en_attente_paiement', max_length=30)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('renouvellement_auto', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='payments.payment')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='pharmacies.pharmacy')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='transactions.transaction')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Abonnement pharmacie',
                'verbose_name_plural': 'Abonnements pharmacies',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['pharmacy', 'statut'], name='subscriptio_pharmac_63020b_idx'), models.Index(fields=['plan', 'statut'], name='subscriptio_plan_id_35dea0_idx'), models.Index(fields=['date_fin'], name='subscriptio_date_fi_45463f_idx')],
            },
        ),
    ]
