# Generated by Django 6.0.4 on 2026-06-15 12:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0007_alter_pharmacy_coordinates_nullable'),
        ('subscriptions', '0002_default_subscription_plans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankily_number', models.CharField(blank=True, max_length=50)),
                ('masrivi_number', models.CharField(blank=True, max_length=50)),
                ('click_number', models.CharField(blank=True, max_length=50)),
                ('sedad_number', models.CharField(blank=True, max_length=50)),
                ('bci_pay_number', models.CharField(blank=True, max_length=50)),
                ('beneficiary_name', models.CharField(blank=True, max_length=150)),
                ('payment_instructions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration paiement plateforme',
                'verbose_name_plural': 'Configurations paiement plateforme',
            },
        ),
        migrations.AlterField(
            model_name='pharmacysubscription',
            name='statut',
            field=models.CharField(choices=[('active', 'Active'), ('expiree', 'Expiree'), ('annulee', 'Annulee'), ('en_attente_paiement', 'En attente paiement'), ('en_attente_validation', 'En attente validation'), ('refuse', 'Refusee')], db_index=True, default='en_attente_paiement', max_length=30),
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_method', models.CharField(choices=[('bankily', 'Bankily'), ('masrivi', 'Masrivi'), ('click', 'Click'), ('sedad', 'Sedad'), ('bci_pay', 'BCI Pay')], max_length=30)),
                ('transaction_id', models.CharField(max_length=150)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='subscriptions/proofs/')),
                ('status', models.CharField(choices=[('en_attente_validation', 'En attente validation'), ('valide', 'Valide'), ('refuse', 'Refuse'), ('annule', 'Annule')], db_index=True, default='en_attente_validation', max_length=30)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='pharmacies.pharmacy')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='subscriptions.pharmacysubscription')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_subscription_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement abonnement',
                'verbose_name_plural': 'Paiements abonnements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='subscriptio_status_9569df_idx'), models.Index(fields=['pharmacy', 'status'], name='subscriptio_pharmac_420dbf_idx')],
            },
        ),
    ]
