# Generated by Django 6.0.4 on 2026-04-26 15:59

from django.db import migrations, models


def sync_validation_status(apps, schema_editor):
    Pharmacy = apps.get_model('pharmacies', 'Pharmacy')
    Pharmacy.objects.filter(est_valide=True).update(statut_validation='validee')
    Pharmacy.objects.filter(est_valide=False).update(statut_validation='en_attente')


def reverse_sync_validation_status(apps, schema_editor):
    Pharmacy = apps.get_model('pharmacies', 'Pharmacy')
    Pharmacy.objects.update(statut_validation='en_attente')


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0004_pharmacy_date_modification'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='motif_refus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='statut_validation',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validee'), ('refusee', 'Refusee')], default='en_attente', max_length=20),
        ),
        migrations.RunPython(sync_validation_status, reverse_sync_validation_status),
    ]
