# Generated by Django 6.0.4 on 2026-04-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0005_pharmacy_date_validation_pharmacy_motif_refus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='date_suspension',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='statut_validation',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validee'), ('refusee', 'Refusee'), ('suspendue', 'Suspendue')], default='en_attente', max_length=20),
        ),
    ]
