# Generated by Django 6.0.4 on 2026-06-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_pharmacien_reservation_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='frais_livraison',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='reservation',
            name='mode_retrait',
            field=models.CharField(choices=[('retrait', 'Retrait a la pharmacie'), ('livraison', 'Livraison a domicile')], default='retrait', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='montant_medicaments',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='reservation',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='reservation',
            name='statut_paiement',
            field=models.CharField(choices=[('non_paye', 'Non paye'), ('en_attente_validation', 'En attente de validation'), ('valide', 'Valide'), ('refuse', 'Refuse'), ('annule', 'Annule'), ('rembourse', 'Rembourse')], default='non_paye', max_length=30),
        ),
    ]
