# Generated by Django 6.0.4 on 2026-06-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_manual_payment_delivery_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmee'), ('en_preparation', 'En preparation'), ('prete_a_retirer', 'Prete a retirer'), ('retiree', 'Retiree'), ('prete', 'Prete'), ('en_livraison', 'En livraison'), ('livree', 'Livree'), ('annulee', 'Annulee'), ('refusee', 'Refusee')], db_index=True, default='en_attente', max_length=20),
        ),
    ]
