# Generated by Django 6.0.4 on 2026-06-16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_payment_phone'),
        ('pharmacies', '0008_pharmacy_google_maps_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0500'), max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payee'), ('overdue', 'En retard'), ('cancelled', 'Annulee')], db_index=True, default='pending', max_length=20)),
                ('due_date', models.DateField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_invoices', to='pharmacies.pharmacy')),
            ],
            options={
                'verbose_name': 'Facture commission',
                'verbose_name_plural': 'Factures commissions',
                'ordering': ['-created_at'],
                'unique_together': {('pharmacy', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='CommissionInvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('bankily', 'Bankily'), ('masrivi', 'Masrivi'), ('click', 'Click'), ('sedad', 'Sedad'), ('bci_pay', 'BCI Pay')], max_length=30)),
                ('transaction_id', models.CharField(max_length=150)),
                ('proof_image', models.ImageField(upload_to='commission_invoices/proofs/')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending_validation', 'En attente validation'), ('validated', 'Valide'), ('rejected', 'Refuse')], db_index=True, default='pending_validation', max_length=30)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.commissioninvoice')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_commission_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement facture commission',
                'verbose_name_plural': 'Paiements factures commissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
