import {
  faBoxesStacked,
  faCalendarCheck,
  faChartLine,
  faCheckCircle,
  faClinicMedical,
  faClock,
  faCreditCard,
  faFileInvoice,
  faMoneyBillTrendUp,
  faReceipt,
  faRotateLeft,
  faStar,
  faTruckFast,
  faUserShield,
  faUsers,
} from "@fortawesome/free-solid-svg-icons";

export const pharmacistLinks = [
  {
    label: "Tableau de bord",
    shortLabel: "Home",
    path: "/pharmacien/dashboard",
    icon: faChartLine,
  },
  {
    label: "Profil pharmacie",
    shortLabel: "Profil",
    path: "/pharmacien/pharmacie",
    icon: faClinicMedical,
  },
  {
    label: "Horaires",
    shortLabel: "Horaires",
    path: "/pharmacien/horaires",
    icon: faClock,
  },
  {
    label: "Stocks",
    shortLabel: "Stocks",
    path: "/pharmacien/stocks",
    icon: faBoxesStacked,
  },
  {
    label: "Reservations",
    shortLabel: "Reserv.",
    path: "/pharmacien/reservations",
    icon: faCalendarCheck,
  },
  {
    label: "Avis",
    shortLabel: "Avis",
    path: "/pharmacien/avis",
    icon: faStar,
  },
  {
    label: "Finance",
    shortLabel: "Finance",
    path: "/pharmacien/finance",
    icon: faMoneyBillTrendUp,
  },
  {
    label: "Transactions",
    shortLabel: "Trans.",
    path: "/pharmacien/transactions",
    icon: faReceipt,
  },
  {
    label: "Paiements",
    shortLabel: "Pay.",
    path: "/pharmacien/payments",
    icon: faCreditCard,
  },
  {
    label: "Modes de paiement",
    shortLabel: "Moy.",
    path: "/pharmacien/payment-methods",
    icon: faCreditCard,
  },
  {
    label: "Livraisons",
    shortLabel: "Livr.",
    path: "/pharmacien/deliveries",
    icon: faTruckFast,
  },
  {
    label: "Abonnement",
    shortLabel: "Sub.",
    path: "/pharmacien/subscription",
    icon: faFileInvoice,
  },
  {
    label: "Factures commissions",
    shortLabel: "Comm.",
    path: "/pharmacien/finance/invoices",
    icon: faFileInvoice,
  },
];

export const adminLinks = [
  {
    label: "Dashboard",
    shortLabel: "Admin",
    path: "/admin/dashboard",
    icon: faChartLine,
  },
  {
    label: "Validation pharmacies",
    shortLabel: "Valid.",
    path: "/admin/pharmacies-validation",
    icon: faCheckCircle,
  },
  {
    label: "Utilisateurs",
    shortLabel: "Users",
    path: "/admin/users",
    icon: faUsers,
  },
  {
    label: "Pharmacies",
    shortLabel: "Pharma",
    path: "/admin/pharmacies",
    icon: faClinicMedical,
  },
  {
    label: "Profil",
    shortLabel: "Profil",
    path: "/admin/profil",
    icon: faUserShield,
  },
  {
    label: "Finance",
    shortLabel: "Finance",
    path: "/admin/finance",
    icon: faMoneyBillTrendUp,
  },
  {
    label: "Transactions",
    shortLabel: "Trans.",
    path: "/admin/transactions",
    icon: faReceipt,
  },
  {
    label: "Paiements",
    shortLabel: "Pay.",
    path: "/admin/payments",
    icon: faCreditCard,
  },
  {
    label: "Modes de paiement",
    shortLabel: "Moy.",
    path: "/admin/payment-methods",
    icon: faCreditCard,
  },
  {
    label: "Paiements abonnements",
    shortLabel: "Subs pay.",
    path: "/admin/subscription-payments",
    icon: faMoneyBillTrendUp,
  },
  {
    label: "Remb. abonnements",
    shortLabel: "Sub ref.",
    path: "/admin/subscription-refunds",
    icon: faRotateLeft,
  },
  {
    label: "Remboursements",
    shortLabel: "Refund",
    path: "/admin/refunds",
    icon: faRotateLeft,
  },
  {
    label: "Factures commissions",
    shortLabel: "Comm.",
    path: "/admin/finance/commission-invoices",
    icon: faFileInvoice,
  },
];
