# Generated by Django 6.0.4 on 2026-06-09 14:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacies', '0007_alter_pharmacy_coordinates_nullable'),
        ('reservations', '0003_reservation_frais_livraison_reservation_mode_retrait_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('numero_compte', models.CharField(blank=True, max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Methode de paiement',
                'verbose_name_plural': 'Methodes de paiement',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_medicaments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('montant_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reference_paiement', models.CharField(blank=True, max_length=150)),
                ('capture_paiement', models.ImageField(blank=True, null=True, upload_to='payments/proofs/')),
                ('statut', models.CharField(choices=[('non_paye', 'Non paye'), ('en_attente_validation', 'En attente de validation'), ('valide', 'Valide'), ('refuse', 'Refuse'), ('annule', 'Annule'), ('rembourse', 'Rembourse')], db_index=True, default='en_attente_validation', max_length=30)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('motif_refus', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pharmacies.pharmacy')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='reservations.reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_payments', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentmethod')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['statut', 'date_creation'], name='payments_pa_statut_66a919_idx'), models.Index(fields=['pharmacy', 'statut'], name='payments_pa_pharmac_b451c5_idx'), models.Index(fields=['user', 'statut'], name='payments_pa_user_id_368514_idx')],
            },
        ),
    ]
