# Generated by Django 6.0.4 on 2026-06-14 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_default_payment_methods'),
        ('pharmacies', '0007_alter_pharmacy_coordinates_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankily_number', models.CharField(blank=True, max_length=50)),
                ('masrivi_number', models.CharField(blank=True, max_length=50)),
                ('click_number', models.CharField(blank=True, max_length=50)),
                ('sedad_number', models.CharField(blank=True, max_length=50)),
                ('bci_pay_number', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('pharmacy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods_config', to='pharmacies.pharmacy')),
            ],
            options={
                'verbose_name': 'Configuration paiement pharmacie',
                'verbose_name_plural': 'Configurations paiement pharmacies',
            },
        ),
    ]
