# Generated by Django 6.0.4 on 2026-06-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_manual_payment_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacypaymentmethod',
            name='beneficiary_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pharmacypaymentmethod',
            name='payment_instructions',
            field=models.TextField(blank=True),
        ),
    ]
