# Generated by Django 6.0.4 on 2026-06-09 15:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        ('payments', '0002_default_payment_methods'),
        ('pharmacies', '0007_alter_pharmacy_coordinates_nullable'),
        ('reservations', '0003_reservation_frais_livraison_reservation_mode_retrait_and_more'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_demande', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_approuve', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('motif', models.CharField(choices=[('medicament_indisponible', 'Medicament indisponible'), ('reservation_annulee', 'Reservation annulee'), ('paiement_en_double', 'Paiement en double'), ('erreur_paiement', 'Erreur de paiement'), ('livraison_echouee', 'Livraison echouee'), ('autre', 'Autre')], max_length=40)),
                ('commentaire_admin', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('demande', 'Demande'), ('en_revision', 'En revision'), ('approuve', 'Approuve'), ('refuse', 'Refuse'), ('effectue', 'Effectue')], db_index=True, default='demande', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_remboursement', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='invoices.invoice')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='refund', to='payments.payment')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='pharmacies.pharmacy')),
                ('refund_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executed_refund', to='transactions.transaction')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='reservations.reservation')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_refunds', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_requests', to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remboursement',
                'verbose_name_plural': 'Remboursements',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='RefundStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(blank=True, choices=[('demande', 'Demande'), ('en_revision', 'En revision'), ('approuve', 'Approuve'), ('refuse', 'Refuse'), ('effectue', 'Effectue')], max_length=20)),
                ('nouveau_statut', models.CharField(choices=[('demande', 'Demande'), ('en_revision', 'En revision'), ('approuve', 'Approuve'), ('refuse', 'Refuse'), ('effectue', 'Effectue')], max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('date_changement', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_status_changes', to=settings.AUTH_USER_MODEL)),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='refunds.refund')),
            ],
            options={
                'verbose_name': 'Historique remboursement',
                'verbose_name_plural': 'Historiques remboursements',
                'ordering': ['-date_changement'],
            },
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['statut', 'date_demande'], name='refunds_ref_statut_d39dbe_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['pharmacy', 'statut'], name='refunds_ref_pharmac_e2e335_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['user', 'statut'], name='refunds_ref_user_id_b12446_idx'),
        ),
    ]
