# Generated by Django 6.0.4 on 2026-06-09 14:59

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0002_default_payment_methods'),
        ('pharmacies', '0007_alter_pharmacy_coordinates_nullable'),
        ('reservations', '0003_reservation_frais_livraison_reservation_mode_retrait_and_more'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(db_index=True, max_length=30, unique=True)),
                ('montant_medicaments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('montant_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('statut', models.CharField(choices=[('emise', 'Emise'), ('payee', 'Payee'), ('annulee', 'Annulee'), ('remboursee', 'Remboursee')], db_index=True, default='emise', max_length=20)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/pdf/')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='payments.payment')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='pharmacies.pharmacy')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='reservations.reservation')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_emission'],
                'indexes': [models.Index(fields=['statut', 'date_emission'], name='invoices_in_statut_612a6a_idx'), models.Index(fields=['pharmacy', 'date_emission'], name='invoices_in_pharmac_8aab6e_idx'), models.Index(fields=['user', 'date_emission'], name='invoices_in_user_id_e91a17_idx')],
            },
        ),
    ]
