# Generated by Django 6.0.4 on 2026-06-09 14:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0002_default_payment_methods'),
        ('pharmacies', '0007_alter_pharmacy_coordinates_nullable'),
        ('reservations', '0003_reservation_frais_livraison_reservation_mode_retrait_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('paiement', 'Paiement'), ('commission', 'Commission'), ('remboursement', 'Remboursement'), ('ajustement', 'Ajustement'), ('abonnement', 'Abonnement')], db_index=True, default='paiement', max_length=30)),
                ('montant_brut', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('montant_pharmacie', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('reference_transaction', models.CharField(db_index=True, max_length=80, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.payment')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='pharmacies.pharmacy')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='reservations.reservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['type_transaction', 'date_creation'], name='transaction_type_tr_f19a2f_idx'), models.Index(fields=['pharmacy', 'date_creation'], name='transaction_pharmac_7659fc_idx'), models.Index(fields=['user', 'date_creation'], name='transaction_user_id_600a68_idx')],
                'constraints': [models.UniqueConstraint(fields=('payment', 'type_transaction'), name='unique_transaction_type_per_payment')],
            },
        ),
    ]
