# Generated by Django 6.0.4 on 2026-04-22 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0001_initial'),
        ('pharmacies', '0002_horaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=0)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='medicaments.medicament')),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='pharmacies.pharmacy')),
            ],
            options={
                'unique_together': {('pharmacie', 'medicament')},
            },
        ),
    ]
