# Generated by Django 6.0.4 on 2026-04-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0003_stock_architecture_upgrade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicament',
            options={'ordering': ['nom']},
        ),
        migrations.AddField(
            model_name='medicament',
            name='categorie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicament',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='nom',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
