# Generated by Django 6.0.4 on 2026-04-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaments', '0004_alter_medicament_options_medicament_categorie_and_more'),
        ('pharmacies', '0006_pharmacy_date_suspension_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('pharmacie', 'medicament'), name='unique_stock_per_pharmacy_medicament'),
        ),
    ]
